/// <amd-module name='ebg/layer/nls/ly_studio_ROOT'/>
export = {
	"dijit/nls/loading": {
		loadingState: "Loading...",
		errorState: "Sorry, an error occurred",
		_localized: {
			al: 1,
			ar: 1,
			az: 1,
			bg: 1,
			bs: 1,
			ca: 1,
			cs: 1,
			da: 1,
			de: 1,
			el: 1,
			es: 1,
			eu: 1,
			fi: 1,
			fr: 1,
			he: 1,
			hr: 1,
			hu: 1,
			id: 1,
			it: 1,
			ja: 1,
			kk: 1,
			ko: 1,
			mk: 1,
			nb: 1,
			nl: 1,
			pl: 1,
			pt: 1,
			"pt-pt": 1,
			ro: 1,
			ru: 1,
			sk: 1,
			sl: 1,
			sr: 1,
			sv: 1,
			th: 1,
			tr: 1,
			uk: 1,
			zh: 1,
			"zh-tw": 1,
		},
	},
	"dijit/nls/common": {
		buttonOk: "OK",
		buttonCancel: "Cancel",
		buttonSave: "Save",
		itemClose: "Close",
		_localized: {
			al: 1,
			ar: 1,
			az: 1,
			bg: 1,
			bs: 1,
			ca: 1,
			cs: 1,
			da: 1,
			de: 1,
			el: 1,
			es: 1,
			eu: 1,
			fi: 1,
			fr: 1,
			he: 1,
			hr: 1,
			hu: 1,
			id: 1,
			it: 1,
			ja: 1,
			kk: 1,
			ko: 1,
			mk: 1,
			nb: 1,
			nl: 1,
			pl: 1,
			pt: 1,
			"pt-pt": 1,
			ro: 1,
			ru: 1,
			sk: 1,
			sl: 1,
			sr: 1,
			sv: 1,
			th: 1,
			tr: 1,
			uk: 1,
			zh: 1,
			"zh-tw": 1,
		},
	},
	"dijit/form/nls/validate": {
		invalidMessage: "The value entered is not valid.",
		missingMessage: "This value is required.",
		rangeMessage: "This value is out of range.",
		_localized: {
			al: 1,
			ar: 1,
			az: 1,
			bg: 1,
			bs: 1,
			ca: 1,
			cs: 1,
			da: 1,
			de: 1,
			el: 1,
			es: 1,
			eu: 1,
			fi: 1,
			fr: 1,
			he: 1,
			hr: 1,
			hu: 1,
			id: 1,
			it: 1,
			ja: 1,
			kk: 1,
			ko: 1,
			mk: 1,
			nb: 1,
			nl: 1,
			pl: 1,
			pt: 1,
			"pt-pt": 1,
			ro: 1,
			ru: 1,
			sk: 1,
			sl: 1,
			sr: 1,
			sv: 1,
			th: 1,
			tr: 1,
			uk: 1,
			zh: 1,
			"zh-tw": 1,
		},
	},
	"dijit/form/nls/ComboBox": {
		previousMessage: "Previous choices",
		nextMessage: "More choices",
		_localized: {
			al: 1,
			ar: 1,
			az: 1,
			bg: 1,
			bs: 1,
			ca: 1,
			cs: 1,
			da: 1,
			de: 1,
			el: 1,
			es: 1,
			eu: 1,
			fi: 1,
			fr: 1,
			he: 1,
			hr: 1,
			hu: 1,
			id: 1,
			it: 1,
			ja: 1,
			kk: 1,
			ko: 1,
			mk: 1,
			nb: 1,
			nl: 1,
			pl: 1,
			pt: 1,
			"pt-pt": 1,
			ro: 1,
			ru: 1,
			sk: 1,
			sl: 1,
			sr: 1,
			sv: 1,
			th: 1,
			tr: 1,
			uk: 1,
			zh: 1,
			"zh-tw": 1,
		},
	},
	"dijit/_editor/nls/commands": {
		bold: "Bold",
		copy: "Copy",
		cut: "Cut",
		delete: "Delete",
		indent: "Indent",
		insertHorizontalRule: "Horizontal Rule",
		insertOrderedList: "Numbered List",
		insertUnorderedList: "Bullet List",
		italic: "Italic",
		justifyCenter: "Align Center",
		justifyFull: "Justify",
		justifyLeft: "Align Left",
		justifyRight: "Align Right",
		outdent: "Outdent",
		paste: "Paste",
		redo: "Redo",
		removeFormat: "Remove Format",
		selectAll: "Select All",
		strikethrough: "Strikethrough",
		subscript: "Subscript",
		superscript: "Superscript",
		underline: "Underline",
		undo: "Undo",
		unlink: "Remove Link",
		createLink: "Create Link",
		toggleDir: "Toggle Direction",
		insertImage: "Insert Image",
		insertTable: "Insert/Edit Table",
		toggleTableBorder: "Toggle Table Border",
		deleteTable: "Delete Table",
		tableProp: "Table Property",
		htmlToggle: "HTML Source",
		foreColor: "Foreground Color",
		hiliteColor: "Background Color",
		plainFormatBlock: "Paragraph Style",
		formatBlock: "Paragraph Style",
		fontSize: "Font Size",
		fontName: "Font Name",
		tabIndent: "Tab Indent",
		fullScreen: "Toggle Full Screen",
		viewSource: "View HTML Source",
		print: "Print",
		newPage: "New Page",
		systemShortcut:
			'The "${0}" action is only available in your browser using a keyboard shortcut. Use ${1}.',
		ctrlKey: "ctrl+${0}",
		appleKey: "âŒ˜${0}",
		_localized: {
			al: 1,
			ar: 1,
			az: 1,
			bg: 1,
			bs: 1,
			ca: 1,
			cs: 1,
			da: 1,
			de: 1,
			el: 1,
			es: 1,
			eu: 1,
			fi: 1,
			fr: 1,
			he: 1,
			hr: 1,
			hu: 1,
			id: 1,
			it: 1,
			ja: 1,
			kk: 1,
			ko: 1,
			mk: 1,
			nb: 1,
			nl: 1,
			pl: 1,
			pt: 1,
			"pt-pt": 1,
			ro: 1,
			ru: 1,
			sk: 1,
			sl: 1,
			sr: 1,
			sv: 1,
			th: 1,
			tr: 1,
			uk: 1,
			zh: 1,
			"zh-tw": 1,
		},
	},
	"dijit/_editor/nls/FontChoice": {
		"1": "xx-small",
		"2": "x-small",
		"3": "small",
		"4": "medium",
		"5": "large",
		"6": "x-large",
		"7": "xx-large",
		fontSize: "Size",
		fontName: "Font",
		formatBlock: "Format",
		serif: "serif",
		"sans-serif": "sans-serif",
		monospace: "monospace",
		cursive: "cursive",
		fantasy: "fantasy",
		noFormat: "None",
		p: "Paragraph",
		h1: "Heading",
		h2: "Subheading",
		h3: "Sub-subheading",
		pre: "Pre-formatted",
		_localized: {
			al: 1,
			ar: 1,
			az: 1,
			bg: 1,
			bs: 1,
			ca: 1,
			cs: 1,
			da: 1,
			de: 1,
			el: 1,
			es: 1,
			eu: 1,
			fi: 1,
			fr: 1,
			he: 1,
			hr: 1,
			hu: 1,
			id: 1,
			it: 1,
			ja: 1,
			kk: 1,
			ko: 1,
			mk: 1,
			nb: 1,
			nl: 1,
			pl: 1,
			pt: 1,
			"pt-pt": 1,
			ro: 1,
			ru: 1,
			sk: 1,
			sl: 1,
			sr: 1,
			sv: 1,
			th: 1,
			tr: 1,
			uk: 1,
			zh: 1,
			"zh-tw": 1,
		},
	},
};
