
/**
 * The dependencies that are valid requirements for defining a game class on BGA. This is used in the `define` function to define the game class. This is pulled directly from the BGA source code, however, some obscure dependencies may be changed or removed from the BGA api in future updates so use with caution.
 */
type BGA_Dependency =
	'dojo' |
	'dijit/Dialog' |
	'dojo/i18n' |
	'dojo/touch' |
	'dojo/window' |
	'dojo/dnd/Moveable' |
	'dojo/dnd/common' |
	'dojo/dnd/Mover' |
	'dojo/dnd/autoscroll' |
	'dojo/dnd/TimedMoveable' |
	'dijit/focus' |
	'dojo/Stateful' |
	'dijit/a11y' |
	'dijit/main' |
	'dijit/registry' |
	'dijit/_base/manager' |
	'dijit/_Widget' |
	'dijit/_WidgetBase' |
	'dijit/Destroyable' |
	'dijit/_OnDijitClickMixin' |
	'dijit/a11yclick' |
	'dijit/_FocusMixin' |
	'dojo/uacss' |
	'dijit/hccss' |
	'dojo/hccss' |
	'dijit/_TemplatedMixin' |
	'dojo/cache' |
	'dojo/text' |
	'dojo/request' |
	'dojo/request/default' |
	'dojo/string' |
	'dijit/_AttachMixin' |
	'dijit/_CssStateMixin' |
	'dijit/form/_FormMixin' |
	'dijit/_DialogMixin' |
	'dijit/DialogUnderlay' |
	'dijit/BackgroundIframe' |
	'dijit/Viewport' |
	'dijit/layout/ContentPane' |
	'dijit/_Container' |
	'dijit/layout/_ContentPaneResizeMixin' |
	'dijit/layout/utils' |
	'dojo/html' |
	'dojo/parser' |
	'dojo/_base/url' |
	'dojo/promise/all' |
	'dojo/date/stamp' |
	'dojox/html/entities' |
	'dojo/fx' |
	'dojo/io/iframe' |
	'dojo/request/iframe' |
	'dojo/NodeList-manipulate' |
	'dijit/Tooltip' |
	'dijit/place' |
	'dojox/uuid/generateRandomUuid' |
	'dojox/uuid/_base' |
	'dojo/back' |
	'dojo/hash' |
	'dojox/dtl/filter/strings' |
	'dojox/string/tokenize' |
	'dojox/string/sprintf' |
	'dojox/dtl/filter/htmlstrings' |
	'dojox/dtl/_base' |
	'dojox/string/Builder' |
	'dijit/form/FilteringSelect' |
	'dijit/form/MappedTextBox' |
	'dijit/form/ValidationTextBox' |
	'dijit/form/TextBox' |
	'dijit/form/_FormValueWidget' |
	'dijit/form/_FormWidget' |
	'dijit/form/_FormWidgetMixin' |
	'dijit/form/_FormValueMixin' |
	'dijit/form/_TextBoxMixin' |
	'dijit/form/ComboBoxMixin' |
	'dojo/store/util/QueryResults' |
	'dijit/form/_AutoCompleterMixin' |
	'dojo/regexp' |
	'dijit/form/DataList' |
	'dojo/store/Memory' |
	'dojo/store/util/SimpleQueryEngine' |
	'dijit/form/_SearchMixin' |
	'dijit/form/_ComboBoxMenu' |
	'dijit/form/_ComboBoxMenuMixin' |
	'dijit/form/_ListMouseMixin' |
	'dijit/form/_ListBase' |
	'dijit/_HasDropDown' |
	'dijit/popup' |
	'dijit/Editor' |
	'dijit/Toolbar' |
	'dijit/_KeyNavContainer' |
	'dijit/_KeyNavMixin' |
	'dijit/ToolbarSeparator' |
	'dijit/layout/_LayoutWidget' |
	'dijit/_Contained' |
	'dijit/form/ToggleButton' |
	'dijit/form/Button' |
	'dijit/form/_ButtonMixin' |
	'dijit/form/_ToggleButtonMixin' |
	'dijit/_editor/_Plugin' |
	'dijit/_editor/plugins/EnterKeyHandling' |
	'dijit/_editor/RichText' |
	'dijit/selection' |
	'dijit/_editor/range' |
	'dijit/_editor/html' |
	'dijit/_editor/plugins/FontChoice' |
	'dijit/_WidgetsInTemplateMixin' |
	'dijit/_editor/plugins/TextColor' |
	'dojo/colors' |
	'dijit/form/DropDownButton' |
	'dijit/_editor/plugins/LinkDialog' |
	'dijit/_editor/plugins/ViewSource' |
	'ebg/core/core' |
	'ebg/core/common' |
	'dojo/date' |
	'dojo/fx/easing' |
	'ebg/core/i18n' |
	'ebg/webrtc' |
	'ebg/peerconnect' |
	'ebg/scriptlogger' |
	'ebg/webpush' |
	'ebg/draggable' |
	'ebg/resizable' |
	'ebg/popindialog' |
	'ebg/gamenotif' |
	'ebg/core/gamegui' |
	'dijit/TooltipDialog' |
	'ebg/core/sitecore' |
	'ebg/core/soundManager' |
	'dijit/form/Select' |
	'dijit/form/_FormSelectWidget' |
	'dojo/data/util/sorter' |
	'dijit/DropDownMenu' |
	'dijit/_MenuBase' |
	'dijit/MenuItem' |
	'dijit/MenuSeparator' |
	'ebg/chatinput' |
	'ebg/thumb' |
	'ebg/playerlocation' |
	'ebg/pageheader' |
	'ebg/tableresults' |
	'ebg/paymentbuttons' |
	'ebg/expandablesection' |
	'ebg/comboajax' |
	'dojox/data/QueryReadStore' |
	'dojox/main' |
	'ebg/counter' |
	'ebg/scrollmap' |
	'ebg/stock' |
	'ebg/dices' |
	'ebg/premiumpanel' |
	'dojox/fx' |
	'dojox/fx/_base' |
	'ebg/wrapper' |
	'ebg/zone' |
	'dojo/selector/acme' |
	
	// dojo.js
	'dojo/main' |
	'dojo/_base/kernel' |
	'dojo/global' |
	'dojo/has' |
	'dojo/_base/config' |
	'dojo/sniff' |
	'dojo/_base/lang' |
	'dojo/_base/array' |
	'dojo/ready' |
	'dojo/domReady' |
	'dojo/_base/declare' |
	'dojo/_base/connect' |
	'dojo/on' |
	'dojo/topic' |
	'dojo/Evented' |
	'dojo/aspect' |
	'dojo/_base/event' |
	'dojo/dom-geometry' |
	'dojo/_base/window' |
	'dojo/dom' |
	'dojo/dom-style' |
	'dojo/mouse' |
	'dojo/_base/sniff' |
	'dojo/keys' |
	'dojo/_base/Deferred' |
	'dojo/Deferred' |
	'dojo/errors/CancelError' |
	'dojo/errors/create' |
	'dojo/promise/Promise' |
	'dojo/promise/instrumentation' |
	'dojo/promise/tracer' |
	'dojo/when' |
	'dojo/_base/json' |
	'dojo/json' |
	'dojo/_base/Color' |
	'dojo/_base/browser' |
	'dojo/_base/unload' |
	'dojo/_base/html' |
	'dojo/dom-attr' |
	'dojo/dom-prop' |
	'dojo/dom-construct' |
	'dojo/dom-class' |
	'dojo/_base/NodeList' |
	'dojo/query' |
	'dojo/selector/_loader' |
	'dojo/NodeList-dom' |
	'dojo/_base/xhr' |
	'dojo/io-query' |
	'dojo/dom-form' |
	'dojo/request/watch' |
	'dojo/request/util' |
	'dojo/errors/RequestError' |
	'dojo/errors/RequestTimeoutError' |
	'dojo/request/xhr' |
	'dojo/request/handlers' |
	'dojo/_base/fx' |
	'dojo/_base/loader' |

	'dojo/_firebug/firebug';